### ISSUE TITLE
Allow configuring tslint to fail on warnings

### ISSUE THREAD

**Issue by pelotom** [zinserjan/ts-checker-webpack-plugin#27]
Hi, this is a great plugin, thanks for making it! I've replaced `tslint-loader` with it because it's much faster. However, one thing I'm missing from that loader is the `failOnHint` option, which will fail the build if any lint warnings occur. I want to turn this on specifically when building in CI, but not when developing locally.

**Comment by zinserjan** [comment]
Yep, the option makes sense.
